### ISSUE TITLE
Synthesized data generation

### ISSUE THREAD

**Issue by Advocate99** [LiheYoung/FreeMask#1]
Hi. Since the FreestyleNet takes text and layout as input, what are the prompts that you used for generating data?
How to automatically set different prompts for multiple generation?

**Comment by LiheYoung** [comment]
Hi, thank you for your question. 

We use the default setting of FreestyleNet, which simply feeds a combination of all class names as the text prompt. As for diverse synthetic images from a single semantic mask, we indeed do not change the text prompt, but just use different random seeds for synthesis. You can check the synthetic datasets we provided, where we add the seed information to the filename suffix.

To better address the concerns about the generation process, we will provide a more detailed description in the README in two weeks. Thank you.

**Comment by Advocate99** [comment]
Thanks for your explanation.
