### ISSUE TITLE
[Datasets Sharepoint Issue] The file size exceeds the allowed limit. 

### ISSUE THREAD

**Issue by apiwhichway** [LiheYoung/FreeMask#2]
Hi @LiheYoung,

I received an error when trying to download the ADE20K_Synthetic.zip file from OneDrive SharePoint.
The error message stated:

----------------------------------------

The file size exceeds the allowed limit.
CorrelationId: b3dc19da-f990-432e-95f5-5e3e26e50e35,
UTC DateTime: 11/08/2023 13:35:48

----------------------------------------

Would you be able to split the dataset into smaller collections and re-upload them? 

Many thanks

**Comment by LiheYoung** [comment]
Hi, thank you for your feedback. I will re-upload them after Nov 17 (CVPR deadline). Thank you for understanding.

**Comment by LiheYoung** [comment]
Hi, I re-checked it and found the file size is not very large (~30G). It can be downloaded with the Chrome browser.

**Comment by apiwhichway** [comment]
Thanks for your re-check.

 By the way, good luck with your CVPR submission!
