### ISSUE TITLE
The code of filtering criterion and sampling principle

### ISSUE THREAD

**Issue by ModulatedConvolutionalNetworks** [LiheYoung/FreeMask#3]
Hello, would you have plan to release the code of filtering criterion and sampling principle, Thanks!

**Comment by LiheYoung** [comment]
Sure. We will release this part after the CVPR deadline.

**Comment by ModulatedConvolutionalNetworks** [comment]
Hi, I'm dying to see and learn the code of filtering criterion and sampling principle , and I want to know when the code  will be released, Thanks!

**Comment by LiheYoung** [comment]
Hi, I have uploaded the code of filtering and resampling. Thank you for your attention.

**Comment by songxueXS** [comment]
Hi, may I ask what model is used when calculating the class-wise average loss on the coco datasets?

**Comment by LiheYoung** [comment]
I trained a SegFormer-B4 model on the real COCO-Stuff dataset by myself.
