### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by songxueXS** [LiheYoung/FreeMask#4]
When I ran filter.py, I encountered this error. RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by LiheYoung** [comment]
Please check whether your semantic masks contain values larger than 150.

**Comment by songxueXS** [comment]
I am conducting experiments on the coco data set, so the semantic masks contain values setting is 183.

**Comment by LiheYoung** [comment]
The largest class index on COCO is 170. You need to firstly convert the masks following [this](https://github.com/open-mmlab/mmsegmentation/blob/main/docs/en/user_guides/2_dataset_prepare.md#coco-stuff-164k).

**Comment by songxueXS** [comment]
So the semantic masks contain values is 171 on the coco dataset? In addition, when filtering categories, should the filtered category value be 255? and line79 in filter.py, mask does not need to be reduced by 1.
line68: class_wise_mean_loss = [(0, 0) for _ in range(150)]
line82: if class_ == 0:
line79: loss = criterion(preds, mask-1)

**Comment by LiheYoung** [comment]
Yes. You are right. The valid values in processed COCO masks should be 0-170 (both included), with the value 255 indicating the ignored regions. And you need to change the filtered value from 0 to 255. And the mask does not need to substracted by 1. Apart from the lines you mentioned, there are some other lines need to be modified:
1. https://github.com/LiheYoung/FreeMask/blob/ad0fde0e579588b8498a842f07070bbe30a2d64b/preprocess/filter.py#L66 The ``ignore_index`` should be 255 for COCO.
2. https://github.com/LiheYoung/FreeMask/blob/ad0fde0e579588b8498a842f07070bbe30a2d64b/preprocess/filter.py#L84-L85 https://github.com/LiheYoung/FreeMask/blob/ad0fde0e579588b8498a842f07070bbe30a2d64b/preprocess/filter.py#L104 https://github.com/LiheYoung/FreeMask/blob/ad0fde0e579588b8498a842f07070bbe30a2d64b/preprocess/filter.py#L109 Do not need the ``-1``.
