### ISSUE TITLE
Suggetions about how to achieve domain-specific semantic image synthesis

### ISSUE THREAD

**Issue by wh-isper** [LiheYoung/FreeMask#5]
Hi, author! Thanks for your great work. I have a question about how to achieve domain-specific semantic image synthesis. For example, I want to use a semantic mask from Cityscapes and an image from GTA5 as style references to generate a GTA5-styled image in an unsupervised domain adaptation (UDA) task. Compared with FreeMask, I add an image for style references. Do you have any ideas about how to deal with this additional image to obtain style information for FreeStyleNet? Looking forward to your reply.

**Comment by LiheYoung** [comment]
Thank you for your interest. I think the simplest strategy may be fine-tuning a new FreestyleNet on GTAV dataset. Then you can directly feed the masks to the new FreestyleNet to generate GTAV-like images.

**Comment by wh-isper** [comment]
Thank you for your reply!
